const MENU_SECTIONS = [
  {
    id: "alkol",
    title: "Alkollü İçecekler",
    items: [
      { name: "Rakı Duble", price: 350 },
      { name: "Bira", price: 200 },
      { name: "Votka", price: 300 },
      { name: "Chivas Viski", price: 500 },
      { name: "Diğer Viskiler", price: 500 },
      { name: "Enerji İçeceği", price: 150 },
      { name: "Küçük Şalgam", price: 50 },
      { name: "Büyük Şalgam", price: 150 },
      { name: "20'lik Rakı", price: 900 },
      { name: "35'lik Rakı", price: 1400 },
      { name: "50'lik Rakı", price: 2100 },
      { name: "70'lik Rakı", price: 2800 },
      { name: "100'lük Rakı", price: 4200 },
      { name: "Diğer Rakılar", price: 400 },
    ],
  },
  {
    id: "mezeler",
    title: "Mezeler & Soğuk Başlangıçlar",
    items: [
      { name: "Mezeler", price: 150 },
      { name: "Beyin", price: 200 },
      { name: "Enginar", price: 200 },
      { name: "Salata Tek", price: 200 },
      { name: "Salata Duble", price: 400 },
      { name: "Ordövr", price: 400 },
      { name: "Meyve Tek", price: 200 },
      { name: "Meyve Duble", price: 400 },
      { name: "Cips Tek", price: 200 },
      { name: "Cips Duble", price: 400 },
    ],
  },
  {
    id: "icecekler",
    title: "İçecekler",
    items: [
      { name: "Kola · Fanta · M. Suyu", price: 100 },
      { name: "Soda", price: 50 },
      { name: "Su", price: 25 },
      { name: "Nescafe", price: 100 },
      { name: "Türk Kahvesi", price: 100 },
    ],
  },
  {
    id: "atistirmalik",
    title: "Atıştırmalıklar",
    items: [
      { name: "Çerez Duble", price: 150 },
      { name: "Çerez Tek", price: 100 },
      { name: "Paçanga Tane", price: 200 },
      { name: "Patates Ekmeği", price: 200 },
      { name: "Kaşar Porsiyon", price: 250 },
      { name: "Peynir Tabağı", price: null },
      { name: "Kuver", price: null },
      { name: "Sigara Böreği Porsiyon", price: 200 },
      { name: "Peynir Porsiyon", price: 150 },
      { name: "Kavun · Peynir", price: 300 },
      { name: "Tost", price: 200 },
      { name: "Köfte Ekmeği", price: 300 },
      { name: "Hamburger", price: 300 },
    ],
  },
  {
    id: "ana-yemek",
    title: "Ana Yemekler",
    items: [
      { name: "Köfte", price: 500 },
      { name: "Tavuk", price: 400 },
      { name: "Ciğer", price: 600 },
      { name: "Kavurma", price: 750 },
      { name: "Et Sote", price: 750 },
      { name: "Şiş", price: 650 },
      { name: "Pirzola", price: 800 },
      { name: "Karışık Izgara", price: 900 },
    ],
  },
];
